/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Clean starter kit
 * Contains headless endpoints for search, dictionaries and forms
 * OpenAPI spec version: Latest
 */

export type EventMessageTypeModel = typeof EventMessageTypeModel[keyof typeof EventMessageTypeModel];


export const EventMessageTypeModel = {
  Default: 'Default',
  Info: 'Info',
  Error: 'Error',
  Success: 'Success',
  Warning: 'Warning',
} as const;
