/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Clean starter kit
 * Contains headless endpoints for search, dictionaries and forms
 * OpenAPI spec version: Latest
 */
import type { EventMessageTypeModel } from './eventMessageTypeModel';

export interface NotificationHeaderModel {
  message: string;
  category: string;
  type: EventMessageTypeModel;
}
