/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Clean starter kit
 * Contains headless endpoints for search, dictionaries and forms
 * OpenAPI spec version: Latest
 */
import type { SearchResultsItemModel } from './searchResultsItemModel';

export interface SearchResultsModel {
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  count?: number | string | null;
  items?: SearchResultsItemModel[];
}
