/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Clean starter kit
 * Contains headless endpoints for search, dictionaries and forms
 * OpenAPI spec version: Latest
 */
import type { SearchResultsItemModel } from './searchResultsItemModel';

export interface SearchResultsModel {
  /** @nullable */
  count?: number | null;
  items: SearchResultsItemModel[];
}
