/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Clean starter kit
 * Contains headless endpoints for search, dictionaries and forms
 * OpenAPI spec version: Latest
 */

export interface TranslationModel {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  key?: string | null;
  /** @nullable */
  value?: string | null;
}
