/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Clean starter kit
 * Contains headless endpoints for search, dictionaries and forms
 * OpenAPI spec version: Latest
 */
import type {
  TranslationModel
} from '../model';

import { customFetch } from '../../custom-fetch';

export type getApiV1DictionaryGetdictionarytranslationsResponse200ApplicationJson = {
  data: TranslationModel[]
  status: 200
}

export type getApiV1DictionaryGetdictionarytranslationsResponse200TextJson = {
  data: TranslationModel[]
  status: 200
}

export type getApiV1DictionaryGetdictionarytranslationsResponse200TextPlain = {
  data: TranslationModel[]
  status: 200
}

export type getApiV1DictionaryGetdictionarytranslationsResponse500 = {
  data: void
  status: 500
}

export type getApiV1DictionaryGetdictionarytranslationsResponseSuccess = (getApiV1DictionaryGetdictionarytranslationsResponse200ApplicationJson | getApiV1DictionaryGetdictionarytranslationsResponse200TextJson | getApiV1DictionaryGetdictionarytranslationsResponse200TextPlain) & {
  headers: Headers;
};
export type getApiV1DictionaryGetdictionarytranslationsResponseError = (getApiV1DictionaryGetdictionarytranslationsResponse500) & {
  headers: Headers;
};

export type getApiV1DictionaryGetdictionarytranslationsResponse = (getApiV1DictionaryGetdictionarytranslationsResponseSuccess | getApiV1DictionaryGetdictionarytranslationsResponseError)

export const getGetApiV1DictionaryGetdictionarytranslationsUrl = () => {




  return `http://localhost:38357/api/v1/dictionary/getdictionarytranslations`
}

export const getApiV1DictionaryGetdictionarytranslations = async ( options?: RequestInit): Promise<getApiV1DictionaryGetdictionarytranslationsResponse> => {

  return customFetch<getApiV1DictionaryGetdictionarytranslationsResponse>(getGetApiV1DictionaryGetdictionarytranslationsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


