/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Clean starter kit
 * Contains headless endpoints for search, dictionaries and forms
 * OpenAPI spec version: Latest
 */
import type {
  EmailForm
} from '../model';

import { customFetch } from '../../custom-fetch';

export type postApiV1ContactPostContactFormResponse200ApplicationJson = {
  data: boolean
  status: 200
}

export type postApiV1ContactPostContactFormResponse200TextJson = {
  data: boolean
  status: 200
}

export type postApiV1ContactPostContactFormResponse200TextPlain = {
  data: boolean
  status: 200
}

export type postApiV1ContactPostContactFormResponse500 = {
  data: void
  status: 500
}

export type postApiV1ContactPostContactFormResponseSuccess = (postApiV1ContactPostContactFormResponse200ApplicationJson | postApiV1ContactPostContactFormResponse200TextJson | postApiV1ContactPostContactFormResponse200TextPlain) & {
  headers: Headers;
};
export type postApiV1ContactPostContactFormResponseError = (postApiV1ContactPostContactFormResponse500) & {
  headers: Headers;
};

export type postApiV1ContactPostContactFormResponse = (postApiV1ContactPostContactFormResponseSuccess | postApiV1ContactPostContactFormResponseError)

export const getPostApiV1ContactPostContactFormUrl = () => {




  return `http://localhost:43343/api/v1/contact/postContactForm`
}

export const postApiV1ContactPostContactForm = async (emailForm?: EmailForm, options?: RequestInit): Promise<postApiV1ContactPostContactFormResponse> => {

  return customFetch<postApiV1ContactPostContactFormResponse>(getPostApiV1ContactPostContactFormUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(emailForm)
  }
);}


