/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Clean starter kit
 * Contains headless endpoints for search, dictionaries and forms
 * OpenAPI spec version: Latest
 */
import type {
  GetApiV1SearchGetSearchResultsParams,
  SearchResultsModel
} from '../model';

import { customFetch } from '../../custom-fetch';

export type getApiV1SearchGetSearchResultsResponse200ApplicationJson = {
  data: SearchResultsModel
  status: 200
}

export type getApiV1SearchGetSearchResultsResponse200TextJson = {
  data: SearchResultsModel
  status: 200
}

export type getApiV1SearchGetSearchResultsResponse200TextPlain = {
  data: SearchResultsModel
  status: 200
}

export type getApiV1SearchGetSearchResultsResponse500 = {
  data: void
  status: 500
}

export type getApiV1SearchGetSearchResultsResponseSuccess = (getApiV1SearchGetSearchResultsResponse200ApplicationJson | getApiV1SearchGetSearchResultsResponse200TextJson | getApiV1SearchGetSearchResultsResponse200TextPlain) & {
  headers: Headers;
};
export type getApiV1SearchGetSearchResultsResponseError = (getApiV1SearchGetSearchResultsResponse500) & {
  headers: Headers;
};

export type getApiV1SearchGetSearchResultsResponse = (getApiV1SearchGetSearchResultsResponseSuccess | getApiV1SearchGetSearchResultsResponseError)

export const getGetApiV1SearchGetSearchResultsUrl = (params?: GetApiV1SearchGetSearchResultsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:38357/api/v1/search/getSearchResults?${stringifiedParams}` : `http://localhost:38357/api/v1/search/getSearchResults`
}

export const getApiV1SearchGetSearchResults = async (params?: GetApiV1SearchGetSearchResultsParams, options?: RequestInit): Promise<getApiV1SearchGetSearchResultsResponse> => {

  return customFetch<getApiV1SearchGetSearchResultsResponse>(getGetApiV1SearchGetSearchResultsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


