/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiContentRouteModel } from './iApiContentRouteModel';
import type { LinkTypeModel } from './linkTypeModel';

export interface ApiLinkModel {
  /** @nullable */
  url?: string | null;
  /** @nullable */
  queryString?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  target?: string | null;
  /** @nullable */
  destinationId?: string | null;
  /** @nullable */
  destinationType?: string | null;
  route?: IApiContentRouteModel;
  linkType: LinkTypeModel;
  /** @nullable */
  culture?: string | null;
}
