/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { ArticleListContentModelContentType } from './articleListContentModelContentType';
import type { ArticleListContentPropertiesModel } from './articleListContentPropertiesModel';
import type { IApiContentBaseModel } from './iApiContentBaseModel';

export type ArticleListContentModel = IApiContentBaseModel & {
  contentType: ArticleListContentModelContentType;
  properties?: ArticleListContentPropertiesModel;
};
