/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { ContentControlsContentPropertiesModel } from './contentControlsContentPropertiesModel';
import type { HeaderControlsContentPropertiesModel } from './headerControlsContentPropertiesModel';
import type { MainImageControlsContentPropertiesModel } from './mainImageControlsContentPropertiesModel';
import type { SEOControlsContentPropertiesModel } from './sEOControlsContentPropertiesModel';
import type { VisibilityControlsContentPropertiesModel } from './visibilityControlsContentPropertiesModel';

export type AuthorListContentPropertiesModel = ContentControlsContentPropertiesModel & HeaderControlsContentPropertiesModel & MainImageControlsContentPropertiesModel & SEOControlsContentPropertiesModel & VisibilityControlsContentPropertiesModel;
