/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { AuthorContentModel } from './authorContentModel';
import type { AuthorContentResponseModelContentType } from './authorContentResponseModelContentType';
import type { IApiContentResponseModelBase } from './iApiContentResponseModelBase';

export type AuthorContentResponseModel = Omit<IApiContentResponseModelBase & AuthorContentModel, 'contentType'> & {
  contentType: AuthorContentResponseModelContentType;
};
