/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { CategoryListContentModel } from './categoryListContentModel';
import type { CategoryListContentResponseModelContentType } from './categoryListContentResponseModelContentType';
import type { IApiContentResponseModelBase } from './iApiContentResponseModelBase';

export type CategoryListContentResponseModel = Omit<IApiContentResponseModelBase & CategoryListContentModel, 'contentType'> & {
  contentType: CategoryListContentResponseModelContentType;
};
