/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { CategoryListContentModelContentType } from './categoryListContentModelContentType';
import type { CategoryListPropertiesModel } from './categoryListPropertiesModel';
import type { IApiContentModelBase } from './iApiContentModelBase';

export type CategoryListContentModel = Omit<IApiContentModelBase, 'contentType'> & {
  properties?: CategoryListPropertiesModel;
  contentType: CategoryListContentModelContentType;
};
