/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { CodeSnippetRowElementModelContentType } from './codeSnippetRowElementModelContentType';
import type { CodeSnippetRowElementPropertiesModel } from './codeSnippetRowElementPropertiesModel';
import type { IApiElementBaseModel } from './iApiElementBaseModel';

export type CodeSnippetRowElementModel = IApiElementBaseModel & {
  contentType: CodeSnippetRowElementModelContentType;
  properties?: CodeSnippetRowElementPropertiesModel;
};
