/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { ContactFormControlsContentModelContentType } from './contactFormControlsContentModelContentType';
import type { ContactFormControlsContentPropertiesModel } from './contactFormControlsContentPropertiesModel';
import type { IApiContentBaseModel } from './iApiContentBaseModel';

export type ContactFormControlsContentModel = IApiContentBaseModel & {
  contentType: ContactFormControlsContentModelContentType;
  properties?: ContactFormControlsContentPropertiesModel;
};
