/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { ContactContentModelContentType } from './contactContentModelContentType';
import type { ContactPropertiesModel } from './contactPropertiesModel';
import type { IApiContentModelBase } from './iApiContentModelBase';

export type ContactContentModel = Omit<IApiContentModelBase, 'contentType'> & {
  properties?: ContactPropertiesModel;
  contentType: ContactContentModelContentType;
};
