/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { ContentContentModelContentType } from './contentContentModelContentType';
import type { ContentPropertiesModel } from './contentPropertiesModel';
import type { IApiContentModelBase } from './iApiContentModelBase';

export type ContentContentModel = Omit<IApiContentModelBase, 'contentType'> & {
  properties?: ContentPropertiesModel;
  contentType: ContentContentModelContentType;
};
