/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { ErrorContentModelContentType } from './errorContentModelContentType';
import type { ErrorContentPropertiesModel } from './errorContentPropertiesModel';
import type { IApiContentBaseModel } from './iApiContentBaseModel';

export type ErrorContentModel = IApiContentBaseModel & {
  contentType: ErrorContentModelContentType;
  properties?: ErrorContentPropertiesModel;
};
