/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { FileMediaWithCropsModel } from './fileMediaWithCropsModel';
import type { FileMediaWithCropsResponseModelMediaType } from './fileMediaWithCropsResponseModelMediaType';
import type { IApiMediaWithCropsResponseBaseModel } from './iApiMediaWithCropsResponseBaseModel';

export type FileMediaWithCropsResponseModel = IApiMediaWithCropsResponseBaseModel & FileMediaWithCropsModel & {
  mediaType: FileMediaWithCropsResponseModelMediaType;
};
