/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */

export type FolderMediaWithCropsModelMediaType = typeof FolderMediaWithCropsModelMediaType[keyof typeof FolderMediaWithCropsModelMediaType];


export const FolderMediaWithCropsModelMediaType = {
  Folder: 'Folder',
} as const;
