/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { HomeContentModel } from './homeContentModel';
import type { HomeContentResponseModelContentType } from './homeContentResponseModelContentType';
import type { IApiContentResponseBaseModel } from './iApiContentResponseBaseModel';

export type HomeContentResponseModel = IApiContentResponseBaseModel & HomeContentModel & {
  contentType: HomeContentResponseModelContentType;
};
