/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */

export type HomeContentResponseModelContentType = typeof HomeContentResponseModelContentType[keyof typeof HomeContentResponseModelContentType];


export const HomeContentResponseModelContentType = {
  home: 'home',
} as const;
