/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { CategoryElementElementModel } from './categoryElementElementModel';
import type { CodeSnippetRowElementModel } from './codeSnippetRowElementModel';
import type { CodeSnippetRowSettingsElementModel } from './codeSnippetRowSettingsElementModel';
import type { HidePropertyElementModel } from './hidePropertyElementModel';
import type { IconLinkRowElementModel } from './iconLinkRowElementModel';
import type { IconLinkRowSettingsElementModel } from './iconLinkRowSettingsElementModel';
import type { ImageCarouselRowElementModel } from './imageCarouselRowElementModel';
import type { ImageCarouselRowSettingsElementModel } from './imageCarouselRowSettingsElementModel';
import type { ImageRowElementModel } from './imageRowElementModel';
import type { ImageRowSettingsElementModel } from './imageRowSettingsElementModel';
import type { LatestArticlesRowElementModel } from './latestArticlesRowElementModel';
import type { LatestArticlesRowSettingsElementModel } from './latestArticlesRowSettingsElementModel';
import type { ListPageSettingsElementModel } from './listPageSettingsElementModel';
import type { RichTextRowElementModel } from './richTextRowElementModel';
import type { RichTextRowSettingsElementModel } from './richTextRowSettingsElementModel';
import type { SpacingPropertiesElementModel } from './spacingPropertiesElementModel';
import type { VideoRowElementModel } from './videoRowElementModel';
import type { VideoRowSettingsElementModel } from './videoRowSettingsElementModel';

export type IApiElementModel = ListPageSettingsElementModel | ImageCarouselRowElementModel | CategoryElementElementModel | CodeSnippetRowElementModel | ImageRowElementModel | IconLinkRowElementModel | VideoRowElementModel | LatestArticlesRowElementModel | RichTextRowElementModel | SpacingPropertiesElementModel | HidePropertyElementModel | ImageCarouselRowSettingsElementModel | CodeSnippetRowSettingsElementModel | VideoRowSettingsElementModel | IconLinkRowSettingsElementModel | LatestArticlesRowSettingsElementModel | ImageRowSettingsElementModel | RichTextRowSettingsElementModel;
