/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiMediaWithCropsModelProperties } from './iApiMediaWithCropsModelProperties';
import type { ImageCropModel } from './imageCropModel';
import type { ImageFocalPointModel } from './imageFocalPointModel';

export interface IApiMediaWithCropsModel {
  readonly id: string;
  readonly name: string;
  readonly mediaType: string;
  readonly url: string;
  /** @nullable */
  readonly extension?: string | null;
  /** @nullable */
  readonly width?: number | null;
  /** @nullable */
  readonly height?: number | null;
  /** @nullable */
  readonly bytes?: number | null;
  readonly properties: IApiMediaWithCropsModelProperties;
  focalPoint?: ImageFocalPointModel;
  /** @nullable */
  readonly crops?: readonly ImageCropModel[] | null;
}
