/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiMediaWithCropsResponseBaseModelProperties } from './iApiMediaWithCropsResponseBaseModelProperties';
import type { ImageCropModel } from './imageCropModel';
import type { ImageFocalPointModel } from './imageFocalPointModel';

export interface IApiMediaWithCropsResponseBaseModel {
  /** @nullable */
  path: string | null;
  createDate: string;
  updateDate: string;
  focalPoint?: ImageFocalPointModel;
  /** @nullable */
  crops?: ImageCropModel[] | null;
  id: string;
  /** @nullable */
  name: string | null;
  /** @nullable */
  mediaType: string | null;
  /** @nullable */
  url: string | null;
  /** @nullable */
  extension?: string | null;
  /** @nullable */
  width?: number | null;
  /** @nullable */
  height?: number | null;
  /** @nullable */
  bytes?: number | null;
  /** @nullable */
  properties: IApiMediaWithCropsResponseBaseModelProperties;
}
