/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { ArticleContentResponseModel } from './articleContentResponseModel';
import type { ArticleControlsContentResponseModel } from './articleControlsContentResponseModel';
import type { ArticleListContentResponseModel } from './articleListContentResponseModel';
import type { AuthorContentResponseModel } from './authorContentResponseModel';
import type { AuthorListContentResponseModel } from './authorListContentResponseModel';
import type { CategoryContentResponseModel } from './categoryContentResponseModel';
import type { CategoryListContentResponseModel } from './categoryListContentResponseModel';
import type { ContactContentResponseModel } from './contactContentResponseModel';
import type { ContactFormControlsContentResponseModel } from './contactFormControlsContentResponseModel';
import type { ContentContentResponseModel } from './contentContentResponseModel';
import type { ContentControlsContentResponseModel } from './contentControlsContentResponseModel';
import type { ErrorContentResponseModel } from './errorContentResponseModel';
import type { FooterControlsContentResponseModel } from './footerControlsContentResponseModel';
import type { HeaderControlsContentResponseModel } from './headerControlsContentResponseModel';
import type { HomeContentResponseModel } from './homeContentResponseModel';
import type { MainImageControlsContentResponseModel } from './mainImageControlsContentResponseModel';
import type { SearchContentResponseModel } from './searchContentResponseModel';
import type { SEOControlsContentResponseModel } from './sEOControlsContentResponseModel';
import type { VisibilityControlsContentResponseModel } from './visibilityControlsContentResponseModel';
import type { XMLSitemapContentResponseModel } from './xMLSitemapContentResponseModel';

export type IApiContentResponseModel = HeaderControlsContentResponseModel | FooterControlsContentResponseModel | ContactFormControlsContentResponseModel | CategoryContentResponseModel | ContentControlsContentResponseModel | SEOControlsContentResponseModel | VisibilityControlsContentResponseModel | MainImageControlsContentResponseModel | ArticleControlsContentResponseModel | XMLSitemapContentResponseModel | CategoryListContentResponseModel | AuthorContentResponseModel | ContactContentResponseModel | ContentContentResponseModel | SearchContentResponseModel | AuthorListContentResponseModel | HomeContentResponseModel | ErrorContentResponseModel | ArticleListContentResponseModel | ArticleContentResponseModel;
