/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { FileMediaWithCropsModel } from './fileMediaWithCropsModel';
import type { FolderMediaWithCropsModel } from './folderMediaWithCropsModel';
import type { ImageMediaWithCropsModel } from './imageMediaWithCropsModel';
import type { UmbracoMediaArticleMediaWithCropsModel } from './umbracoMediaArticleMediaWithCropsModel';
import type { UmbracoMediaAudioMediaWithCropsModel } from './umbracoMediaAudioMediaWithCropsModel';
import type { UmbracoMediaVectorGraphicsMediaWithCropsModel } from './umbracoMediaVectorGraphicsMediaWithCropsModel';
import type { UmbracoMediaVideoMediaWithCropsModel } from './umbracoMediaVideoMediaWithCropsModel';

export type IApiMediaWithCropsModel = FolderMediaWithCropsModel | ImageMediaWithCropsModel | FileMediaWithCropsModel | UmbracoMediaVideoMediaWithCropsModel | UmbracoMediaAudioMediaWithCropsModel | UmbracoMediaArticleMediaWithCropsModel | UmbracoMediaVectorGraphicsMediaWithCropsModel;
