/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { FileMediaWithCropsResponseModel } from './fileMediaWithCropsResponseModel';
import type { FolderMediaWithCropsResponseModel } from './folderMediaWithCropsResponseModel';
import type { ImageMediaWithCropsResponseModel } from './imageMediaWithCropsResponseModel';
import type { UmbracoMediaArticleMediaWithCropsResponseModel } from './umbracoMediaArticleMediaWithCropsResponseModel';
import type { UmbracoMediaAudioMediaWithCropsResponseModel } from './umbracoMediaAudioMediaWithCropsResponseModel';
import type { UmbracoMediaVectorGraphicsMediaWithCropsResponseModel } from './umbracoMediaVectorGraphicsMediaWithCropsResponseModel';
import type { UmbracoMediaVideoMediaWithCropsResponseModel } from './umbracoMediaVideoMediaWithCropsResponseModel';

export type IApiMediaWithCropsResponseModel = FolderMediaWithCropsResponseModel | ImageMediaWithCropsResponseModel | FileMediaWithCropsResponseModel | UmbracoMediaVideoMediaWithCropsResponseModel | UmbracoMediaAudioMediaWithCropsResponseModel | UmbracoMediaArticleMediaWithCropsResponseModel | UmbracoMediaVectorGraphicsMediaWithCropsResponseModel;
