/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiElementModelBase } from './iApiElementModelBase';
import type { IconLinkRowElementModelContentType } from './iconLinkRowElementModelContentType';
import type { IconLinkRowPropertiesModel } from './iconLinkRowPropertiesModel';

export type IconLinkRowElementModel = Omit<IApiElementModelBase, 'contentType'> & {
  properties?: IconLinkRowPropertiesModel;
  contentType: IconLinkRowElementModelContentType;
};
