/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiElementModelBase } from './iApiElementModelBase';
import type { LatestArticlesRowSettingsElementModelContentType } from './latestArticlesRowSettingsElementModelContentType';
import type { LatestArticlesRowSettingsPropertiesModel } from './latestArticlesRowSettingsPropertiesModel';

export type LatestArticlesRowSettingsElementModel = Omit<IApiElementModelBase, 'contentType'> & {
  properties?: LatestArticlesRowSettingsPropertiesModel;
  contentType: LatestArticlesRowSettingsElementModelContentType;
};
