/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiElementModelBase } from './iApiElementModelBase';
import type { LatestArticlesRowElementModelContentType } from './latestArticlesRowElementModelContentType';
import type { LatestArticlesRowPropertiesModel } from './latestArticlesRowPropertiesModel';

export type LatestArticlesRowElementModel = Omit<IApiElementModelBase, 'contentType'> & {
  properties?: LatestArticlesRowPropertiesModel;
  contentType: LatestArticlesRowElementModelContentType;
};
