/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiElementBaseModel } from './iApiElementBaseModel';
import type { LatestArticlesRowElementModelContentType } from './latestArticlesRowElementModelContentType';
import type { LatestArticlesRowElementPropertiesModel } from './latestArticlesRowElementPropertiesModel';

export type LatestArticlesRowElementModel = IApiElementBaseModel & {
  contentType: LatestArticlesRowElementModelContentType;
  properties?: LatestArticlesRowElementPropertiesModel;
};
