/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiContentModelBase } from './iApiContentModelBase';
import type { MainImageControlsContentModelContentType } from './mainImageControlsContentModelContentType';
import type { MainImageControlsPropertiesModel } from './mainImageControlsPropertiesModel';

export type MainImageControlsContentModel = Omit<IApiContentModelBase, 'contentType'> & {
  properties?: MainImageControlsPropertiesModel;
  contentType: MainImageControlsContentModelContentType;
};
