/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiElementModelBase } from './iApiElementModelBase';
import type { RichTextRowElementModelContentType } from './richTextRowElementModelContentType';
import type { RichTextRowPropertiesModel } from './richTextRowPropertiesModel';

export type RichTextRowElementModel = Omit<IApiElementModelBase, 'contentType'> & {
  properties?: RichTextRowPropertiesModel;
  contentType: RichTextRowElementModelContentType;
};
