/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiContentModelBase } from './iApiContentModelBase';
import type { SearchContentModelContentType } from './searchContentModelContentType';
import type { SearchPropertiesModel } from './searchPropertiesModel';

export type SearchContentModel = Omit<IApiContentModelBase, 'contentType'> & {
  properties?: SearchPropertiesModel;
  contentType: SearchContentModelContentType;
};
