/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiContentBaseModel } from './iApiContentBaseModel';
import type { SEOControlsContentModelContentType } from './sEOControlsContentModelContentType';
import type { SEOControlsContentPropertiesModel } from './sEOControlsContentPropertiesModel';

export type SEOControlsContentModel = IApiContentBaseModel & {
  contentType: SEOControlsContentModelContentType;
  properties?: SEOControlsContentPropertiesModel;
};
