/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */

export type SEocontrolsContentModelContentType = typeof SEocontrolsContentModelContentType[keyof typeof SEocontrolsContentModelContentType];


export const SEocontrolsContentModelContentType = {
  sEOControls: 'sEOControls',
} as const;
