/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */

export interface SpacingPropertiesElementPropertiesModel {
  /** @nullable */
  paddingTop?: string | null;
  /** @nullable */
  paddingBottom?: string | null;
  /** @nullable */
  paddingLeft?: string | null;
  /** @nullable */
  paddingRight?: string | null;
  /** @nullable */
  marginTop?: string | null;
  /** @nullable */
  marginBottom?: string | null;
  /** @nullable */
  marginLeft?: string | null;
  /** @nullable */
  marginRight?: string | null;
}
