/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiMediaWithCropsResponseBaseModel } from './iApiMediaWithCropsResponseBaseModel';
import type { UmbracoMediaVectorGraphicsMediaWithCropsModel } from './umbracoMediaVectorGraphicsMediaWithCropsModel';
import type { UmbracoMediaVectorGraphicsMediaWithCropsResponseModelMediaType } from './umbracoMediaVectorGraphicsMediaWithCropsResponseModelMediaType';

export type UmbracoMediaVectorGraphicsMediaWithCropsResponseModel = IApiMediaWithCropsResponseBaseModel & UmbracoMediaVectorGraphicsMediaWithCropsModel & {
  mediaType: UmbracoMediaVectorGraphicsMediaWithCropsResponseModelMediaType;
};
