/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */

export type UmbracoMediaVectorGraphicsMediaWithCropsResponseModelMediaType = typeof UmbracoMediaVectorGraphicsMediaWithCropsResponseModelMediaType[keyof typeof UmbracoMediaVectorGraphicsMediaWithCropsResponseModelMediaType];


export const UmbracoMediaVectorGraphicsMediaWithCropsResponseModelMediaType = {
  umbracoMediaVectorGraphics: 'umbracoMediaVectorGraphics',
} as const;
