/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiMediaWithCropsBaseModel } from './iApiMediaWithCropsBaseModel';
import type { UmbracoMediaArticleMediaPropertiesModel } from './umbracoMediaArticleMediaPropertiesModel';
import type { UmbracoMediaArticleMediaWithCropsModelMediaType } from './umbracoMediaArticleMediaWithCropsModelMediaType';

export type UmbracoMediaArticleMediaWithCropsModel = IApiMediaWithCropsBaseModel & {
  mediaType: UmbracoMediaArticleMediaWithCropsModelMediaType;
  properties?: UmbracoMediaArticleMediaPropertiesModel;
};
