/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */

export interface UmbracoMediaArticleMediaPropertiesModel {
  /** @nullable */
  umbracoFile?: string | null;
  /** @nullable */
  umbracoExtension?: string | null;
  /** @nullable */
  umbracoBytes?: number | null;
}
