/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiContentBaseModel } from './iApiContentBaseModel';
import type { XMLSitemapContentModelContentType } from './xMLSitemapContentModelContentType';
import type { XMLSitemapContentPropertiesModel } from './xMLSitemapContentPropertiesModel';

export type XMLSitemapContentModel = IApiContentBaseModel & {
  contentType: XMLSitemapContentModelContentType;
  properties?: XMLSitemapContentPropertiesModel;
};
